services:
  devcontainer:
    build: 
      context: .
      dockerfile: Dockerfile
    volumes:
      - ../..:/workspaces:cached      
    network_mode: service:db
    command: sleep infinity
    
  db:
    image: mysql:8.0-debian
    restart: unless-stopped
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 'secret'
      MYSQL_DATABASE: 'ecomm'
    ports:
      - '3306:3306'
    expose:
      - '3306'
      
volumes:
  mysql-data:
